//
// Created by Samarth Mahendra on 2/28/26.
//

#ifndef BUILTIN_FUNCTIONS_H
#define BUILTIN_FUNCTIONS_H
#pragma once
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include "function_registry.h"

namespace orion::distributed {

    inline void register_builtin_functions(FunctionRegistry& registry) {

        registry.register_function("add",
            [](std::vector<std::any> args) -> std::any {
                if (args.size() < 2)
                    throw std::runtime_error("add: expected 2 args, got " +
                                             std::to_string(args.size()));
                int a = std::any_cast<int>(args[0]);
                int b = std::any_cast<int>(args[1]);
                return a + b;
            });

        registry.register_function("mul",
            [](std::vector<std::any> args) -> std::any {
                if (args.size() < 2)
                    throw std::runtime_error("mul: expected 2 args, got " +
                                             std::to_string(args.size()));
                int a = std::any_cast<int>(args[0]);
                int b = std::any_cast<int>(args[1]);
                return a * b;
            });

        registry.register_function("compile_util",
            [](std::vector<std::any> args) -> std::any {
                if (args.empty()) return 0;
                int i = std::any_cast<int>(args[0]);
                std::string cmd = "clang++ -std=c++23 -O2 -fconstexpr-steps=100000000 -c bench_util_" + std::to_string(i) + ".cpp -o dist_obj_util_" + std::to_string(i) + ".o";
                int ret = std::system(cmd.c_str());
                return (ret == 0) ? 1 : 0;
            });

        registry.register_function("compile_main",
            [](std::vector<std::any> args) -> std::any {
                std::string cmd = "clang++ -std=c++23 -O2 -fconstexpr-steps=100000000 -c bench_main.cpp -o dist_obj_main.o";
                int ret = std::system(cmd.c_str());
                return (ret == 0) ? 1 : 0;
            });

        registry.register_function("shell_execute",
            [](std::vector<std::any> args) -> std::any {
                if (args.empty()) return 0;
                // The command string is packed into the first argument as a raw string
                std::string command = std::any_cast<std::string>(args[0]);
                
                // Execute the command
                int ret = std::system(command.c_str());
                return (ret == 0) ? 1 : 0;
            });

        registry.register_function("gen_header",
            [](std::vector<std::any> args) -> std::any {
                if (args.empty()) return 0;
                int i = std::any_cast<int>(args[0]);
                std::ofstream out("bench_util_" + std::to_string(i) + ".h");
                out << "// Generated by Orion Task " << i << "\n"
                    << "long long bench_func_" << i << "(long long val);\n";
                return 1;
            });

        registry.register_function("link_exec",
            [](std::vector<std::any> args) -> std::any {
                // Link all the utility objects and the main object into bench_exec_dist
                // In a real system, the orchestrator passes dependencies. Here we assume all are present.
                std::string cmd = "clang++ -std=c++23 -O2 dist_obj_util_*.o dist_obj_main.o -o bench_exec_dist";
                int ret = std::system(cmd.c_str());
                return (ret == 0) ? 1 : 0;
            });

        registry.register_function("compile_test_project_unit",
            [](std::vector<std::any> args) -> std::any {
                if (args.empty()) return 0;

                const int index = std::any_cast<int>(args[0]);
                std::filesystem::create_directories("test_project/build/distributed");

                std::string cmd =
                    "clang++ -std=c++23 -O2 -fconstexpr-steps=4000000 "
                    "-Itest_project/include "
                    "-c test_project/src/module_" + std::to_string(index) + ".cpp "
                    "-o test_project/build/distributed/module_" + std::to_string(index) + ".o";
                int ret = std::system(cmd.c_str());
                return (ret == 0) ? 1 : 0;
            });

        registry.register_function("compile_test_project_main",
            [](std::vector<std::any>) -> std::any {
                std::filesystem::create_directories("test_project/build/distributed");
                std::string cmd =
                    "clang++ -std=c++23 -O2 -fconstexpr-steps=4000000 "
                    "-Itest_project/include "
                    "-c test_project/src/main.cpp "
                    "-o test_project/build/distributed/main.o";
                int ret = std::system(cmd.c_str());
                return (ret == 0) ? 1 : 0;
            });

        registry.register_function("link_test_project_exec",
            [](std::vector<std::any>) -> std::any {
                std::filesystem::create_directories("test_project/build/distributed");
                std::string cmd =
                    "clang++ -std=c++23 -O2 "
                    "test_project/build/distributed/module_*.o "
                    "test_project/build/distributed/main.o "
                    "-o test_project/build/distributed/test_project_app";
                int ret = std::system(cmd.c_str());
                return (ret == 0) ? 1 : 0;
            });

    }

}
#endif //BUILTIN_FUNCTIONS_H
